### ISSUE TITLE
how can I hide this pannel?

### ISSUE THREAD

**Issue by mohammadmohammadiarchangel** [DanteCoder/JoplinPluginNoteVariables#5]
Is there any way to hide this panel?

**Comment by DanteCoder** [comment]
Yes. To hide/show the panel click on the "x^1" button.

**Comment by coorreia** [comment]
how to scroll down variable panel?

**Comment by coorreia** [comment]
i cant scroll down i delete the main %notes variables% note because the vaiable was too big and i cant scroll down  to delete or edit i reinstall the plugin and now i think the main note %note variable% gone the variable i inserted gone but it still cant scroll down if i put to much variables or a big variable and i have no main folder to edit it im missing something?

**Comment by DanteCoder** [comment]
> how to scroll down variable panel?

Nice question, I haven't implemented scroll yet.

**Comment by defrank** [comment]
Not sure if this is more general (because I see the same issue with other plugin icons), but a gear icon is showing instead of the "x^1" icon:
<img width="847" alt="Screen Shot 2022-05-18 at 15 31 34" src="https://user-images.githubusercontent.com/1741229/169166238-85ad5a26-cc58-47bc-bbc5-1da05fdf9c7c.png">

**Comment by defrank** [comment]
Looks like it's only an issue in "Viewer" mode:
<img width="1446" alt="Screen Shot 2022-05-18 at 16 59 47" src="https://user-images.githubusercontent.com/1741229/169174348-ede00565-5fb0-40f8-b025-7d97cf12b8ff.png">
<img width="1439" alt="Screen Shot 2022-05-18 at 17 00 17" src="https://user-images.githubusercontent.com/1741229/169174399-b06fdffa-6686-4be3-a6de-1fcfb8858320.png">

**Comment by zDavidB** [comment]
![CleanShot 2022-07-04 at 08 16 25](https://user-images.githubusercontent.com/11668707/177101854-6bbffbb9-ac99-4db5-bb67-860aa348bd58.png)
I'm seeing the "x^1" displayed as "Aa" (with the Mac os theme installed).

Plugin seems to work ok though, nice work 👍

**Comment by DanteCoder** [comment]
Plugin updated to v2.0.0, the right panel is no longer needed.
Please update to the latest version and check the [Usage](https://github.com/DanteCoder/JoplinPluginNoteVariables#usage).
